name: deploy
on: [push, workflow_dispatch]
permissions:
  pages: write
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir site
          cp index.html model.meta.json scene_extra.json site/
          cd site
          curl -fL "https://drive.usercontent.google.com/download?id=1WLKRGkX-81mZbrO2eMJsmjTALK4Zmr5b&export=download&confirm=t" -o model-23029ae8.p0.wasm
          touch .nojekyll
          ls -la
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: site
      - id: deployment
        uses: actions/deploy-pages@v4
